Repository erkerkiii/gum, pull requests merged in 2023-07, with the labels that each got.

#11 Aspects can't generate to a read-only directory bug is solved.
  Gum.Composer/AspectType.cs
  Gum.Composer/CodeGen/CompositionCodeGenerator.cs
  Gum.Composer/Composition.cs
  Gum.Composer/Generated/AspectType.cs
  Gum.Composer/Generated/Aspects.cs
  Gum.Composer/Generated/Types.gum
  Gum.Composer/IAspect.cs
  Gum.Composer/Internal/AspectDatabase.cs
  Gum.Composer/Unity/Editor/AspectCreationEditor.cs
  Gum.Composer/UserConfig.cs
  Tests/CompositionTests/TestAspects.cs
Labels: bug, enhancement

#12 AspectTypeCatalog class is introduced for replacing AspectType enum at generated folder
  Gum.Composer/CodeGen/CompositionCodeGenerator.cs
  Tests/CompositionTests/TestAspects.cs
Labels: enhancement

#14 Assembly definition filename (tests) changed
  Tests/GumTests.asmdef
Labels: bug
